version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "6001:6001"
    depends_on:
      - mongo
      - mailhog
    # env_file:
    #   - ./backend/.env
    # volumes:
    #   - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # volumes:
    #   - ./frontend:/app

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - LOCALSTACK_TMPDIR=/var/lib/localstack
    volumes:
      - ./localstack-data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  create-bucket:
    image: amazon/aws-cli:2.15.25
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: >
      sh -c "
        if ! aws --endpoint-url=http://localstack:4566 s3 ls | grep -q file-sharing-files; then
          aws --endpoint-url=http://localstack:4566 s3 mb s3://file-sharing-files &&
          echo '✅ Bucket created';
        else
          echo 'ℹ️ Bucket already exists, skipping';
        fi
      "


  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

volumes:
  mongo-data:
