var router = require('express').Router();
const nodemailer = require('nodemailer');
const otp = require('../models/otp');
require("dotenv").config();

router.get("/",async(req,res)=>{

    const mailTransport = nodemailer.createTransport({
      service: 'gmail',
        auth: {
        user: process.env.MAIL_ID,
        pass: process.env.MAIL_PASS
        }
     })  

    const otpNumber = Math.floor(100000 + Math.random() * 900000);
  
    let mailDetails = {
      from: '"File Sharing"<dy55069790@gmail.com>',
      // to: '3219102rn@gmail.com',
      to: `${req.query.mail}`,
      subject: 'OTP for account password',
      // Math.floor(100000 + Math.random() * 900000) is not secure replace it with number generated by crypto
      text: `Your OTP for File sharing app is ${otpNumber}. It will be valid for 10min.`
    };
    
    mailTransport.sendMail(mailDetails, async (err, data) => {
      if(err) {
        console.log('Error occured in sending email:',err.message);
        res.status(500).send(err.message);
      } else {
        console.log("Email send successfull to",req.query.mail);
        try{
          await otp.findOneAndUpdate({email: req.query.mail},{email: req.query.mail, otp: otpNumber},{upsert: true});
          console.log("Otp created successfully");
          res.status(200).send("Otp created successfully");
        }catch(err){
          console.log("Error occured in otp creation",err);
          res.status(500).send("Error Occured in otp creation");
        }
      }
    });
});

module.exports = router;